[2020-07-21 12:13:29,560] [INFO]: {'provider': 'username', 'Data': {'serial_no': '7zWdffH5DsiaUAbrPsKj2X'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-21 12:14:23,449] [INFO]: {'provider': 'username', 'Data': {'serial_no': '7zWdffH5DsiaUAbrPsKj2X'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 15:37:11,516] [INFO]: {'provider': 'username', 'Data': {'serial_no': 'cUQWnX8AKYHmSPRo8Vegdk'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 16:50:46,945] [INFO]: {'provider': 'username', 'Data': {'serial_no': 'cUQWnX8AKYHmSPRo8Vegdk'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 16:50:48,923] [INFO]: {'provider': 'username', 'Data': {'serial_no': 'cUQWnX8AKYHmSPRo8Vegdk'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 16:53:27,733] [INFO]: {'provider': 'username', 'Data': {'serial_no': '2o76GcYaPSwMXFJd6wQsJX'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 16:56:20,578] [INFO]: {'provider': 'username', 'Data': {'serial_no': '2o76GcYaPSwMXFJd6wQsJX'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 16:56:26,704] [INFO]: {'provider': 'username', 'Data': {'serial_no': '2o76GcYaPSwMXFJd6wQsJX'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 16:56:29,302] [INFO]: {'provider': 'username', 'Data': {'serial_no': None}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 16:57:31,621] [INFO]: {'provider': 'username', 'Data': {'serial_no': 'cUQWnX8AKYHmSPRo8Vegdk'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 17:01:55,449] [INFO]: {'provider': 'username', 'Data': {'serial_no': 'gtCVwssufg3RVhs5WxRfcR'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 17:02:43,092] [INFO]: {'provider': 'username', 'Data': {'serial_no': None}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 17:06:37,299] [INFO]: {'provider': 'username', 'Data': {'serial_no': 'PUCT8DkJNpU8vxgkALJGqd'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 17:40:32,497] [INFO]: {'provider': 'username', 'Data': {'serial_no': 'ZNzJa7ipBmgATUm5jxApgS'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 17:41:44,575] [INFO]: {'provider': 'username', 'Data': {'serial_no': 'cUQWnX8AKYHmSPRo8Vegdk'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 19:11:33,028] [INFO]: {'provider': 'username', 'Data': {'serial_no': 'P6ST4fyWsLTKikZ5532P2n'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 19:12:04,859] [INFO]: {'provider': 'username', 'Data': {'serial_no': 'P6ST4fyWsLTKikZ5532P2n'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 19:13:02,284] [INFO]: {'provider': 'username', 'Data': {'serial_no': '2o76GcYaPSwMXFJd6wQsJX'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 19:21:57,611] [INFO]: {'provider': 'username', 'Data': {'serial_no': None}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 19:22:38,054] [INFO]: {'provider': 'username', 'Data': {'serial_no': None}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 19:23:00,041] [INFO]: {'provider': 'username', 'Data': {'serial_no': 'cUQWnX8AKYHmSPRo8Vegdk'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 19:24:11,204] [INFO]: {'provider': 'username', 'Data': {'serial_no': None}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 19:24:21,547] [INFO]: {'provider': 'username', 'Data': {'serial_no': None}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 19:25:43,608] [INFO]: {'provider': 'username', 'Data': {'serial_no': None}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 19:32:19,915] [INFO]: {'provider': 'username', 'Data': {'serial_no': 'NMVgRn5HGuNMYJ4onAetUJ'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 19:33:25,839] [INFO]: {'provider': 'username', 'Data': {'serial_no': 'cUQWnX8AKYHmSPRo8Vegdk'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 19:36:37,246] [INFO]: {'provider': 'username', 'Data': {'serial_no': 'P6ST4fyWsLTKikZ5532P2n'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 19:37:20,253] [INFO]: {'provider': 'username', 'Data': {'serial_no': '1'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 19:37:41,648] [INFO]: {'provider': 'username', 'Data': {'serial_no': 'PUCT8DkJNpU8vxgkALJGqd'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 19:38:50,621] [INFO]: {'provider': 'username', 'Data': {'serial_no': 'PUCT8DkJNpU8vxgkALJGqd'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 19:39:06,593] [INFO]: {'provider': 'username', 'Data': {'serial_no': '  '}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 20:23:53,183] [ERROR]: Exception on /api/services/v1/order_finalize [POST] [in /home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ubuntu/SIH-2020/app/routes.py", line 508, in order_finalize
    assets = assets['assets']
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    the :attr:`before_first_request_funcs` and only exactly once per
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    @setupmethod
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    self.add_template_global(f, name=name)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    from io import StringIO
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    return f
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
  File "/home/ubuntu/SIH-2020/app/routes.py", line 534, in order_finalize
    logger.error(str(e) + "on line no: " + exc_tb.tb_lineno)
NameError: name 'logger' is not defined
[2020-07-23 20:23:56,347] [ERROR]: Exception on /api/services/v1/order_finalize [POST] [in /home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ubuntu/SIH-2020/app/routes.py", line 508, in order_finalize
    assets = assets['assets']
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    the :attr:`before_first_request_funcs` and only exactly once per
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    @setupmethod
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    self.add_template_global(f, name=name)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    from io import StringIO
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    return f
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
  File "/home/ubuntu/SIH-2020/app/routes.py", line 534, in order_finalize
    logger.error(str(e) + "on line no: " + exc_tb.tb_lineno)
NameError: name 'logger' is not defined
[2020-07-23 20:24:10,006] [ERROR]: Exception on /api/services/v1/order_finalize [POST] [in /home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ubuntu/SIH-2020/app/routes.py", line 508, in order_finalize
    assets = assets['assets']
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    the :attr:`before_first_request_funcs` and only exactly once per
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    @setupmethod
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    self.add_template_global(f, name=name)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    from io import StringIO
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    return f
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
  File "/home/ubuntu/SIH-2020/app/routes.py", line 534, in order_finalize
    logger.error(str(e) + "on line no: " + exc_tb.tb_lineno)
NameError: name 'logger' is not defined
[2020-07-23 20:25:28,306] [ERROR]: Exception on /api/services/v1/order_finalize [POST] [in /home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ubuntu/SIH-2020/app/routes.py", line 508, in order_finalize
    assets = assets['assets']
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    the :attr:`before_first_request_funcs` and only exactly once per
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    @setupmethod
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    self.add_template_global(f, name=name)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    from io import StringIO
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    return f
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
  File "/home/ubuntu/SIH-2020/app/routes.py", line 534, in order_finalize
    logger.error(str(e) + "on line no: " + exc_tb.tb_lineno)
NameError: name 'logger' is not defined
