[2020-07-23 20:50:10,090] [INFO]: {'provider': 'username', 'Data': {'serial_no': 'W8CrDHEHjFFnLLoCxznVcq'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 20:55:14,476] [ERROR]: Exception on /api/services/v1/order_finalize [POST] [in /home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ubuntu/SIH-2020/app/routes.py", line 508, in order_finalize
    assets = assets['assets']
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    the :attr:`before_first_request_funcs` and only exactly once per
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    @setupmethod
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    self.add_template_global(f, name=name)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    from io import StringIO
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    return f
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
  File "/home/ubuntu/SIH-2020/app/routes.py", line 534, in order_finalize
    logger.error(str(e) + "on line no: " + exc_tb.tb_lineno)
NameError: name 'logger' is not defined
[2020-07-24 12:46:47,882] [INFO]: {'provider': 'username', 'Data': {'serial_no': 'PUCT8DkJNpU8vxgkALJGqd'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-25 10:52:36,471] [INFO]: {'provider': 'username', 'Data': {'serial_no': 'bis'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-25 10:52:41,190] [INFO]: {'provider': 'username', 'Data': {'serial_no': 'bis1'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-25 10:53:11,733] [INFO]: Inside get asset api [in /home/ubuntu/SIH-2020/app/routes.py:841]
[2020-07-25 10:53:11,734] [INFO]: {'provider': 'username', 'Data': {'username': 'preyash_seller'}} [in /home/ubuntu/SIH-2020/app/routes.py:844]
[2020-07-25 10:53:18,983] [INFO]: {'provider': 'username', 'Data': {'serial_no': 'J9k7PV7m3uGocLPSbdJdYv'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
