[2020-07-29 11:33:01,520] [INFO]: {'provider': 'username', 'Data': {'serial_no': 'Wdfda5jKgUUz2WbYpV7aYc'}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-29 11:33:08,833] [INFO]: Inside get asset api [in /home/ubuntu/SIH-2020/app/routes.py:930]
[2020-07-29 11:33:08,833] [INFO]: {'Data': {'username': 'manav_broker'}} [in /home/ubuntu/SIH-2020/app/routes.py:933]
[2020-07-29 11:43:23,386] [INFO]: {'provider': 'username', 'Data': {'serial_no': 'nDdSyk5aBKvVwZzvtaBdwp'}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-29 11:46:14,195] [INFO]: {'provider': 'username', 'Data': {'serial_no': 'b96vS8QVJjuDPaJwfwhVot'}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-29 12:06:32,483] [INFO]: {'provider': 'username', 'Data': {'serial_no': '7zWdffH5DsiaUAbrPsKj2X'}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-29 12:52:57,765] [INFO]: Inside get asset api [in /home/ubuntu/SIH-2020/app/routes.py:930]
[2020-07-29 12:52:57,765] [INFO]: {'Data': {'username': 'manav_broker'}} [in /home/ubuntu/SIH-2020/app/routes.py:933]
[2020-07-29 13:20:20,057] [INFO]: {'provider': 'username', 'Data': {'serial_no': 'cUQWnX8AKYHmSPRo8Vegdk'}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-29 19:21:36,763] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-29 19:21:37,285] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-29 19:24:01,337] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-29 19:45:39,522] [INFO]: {'provider': 'username', 'Data': {'serial_no': 'NMVgRn5HGuNMYJ4onAetUJ'}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-29 20:34:37,613] [INFO]: {'provider': 'username', 'Data': {'serial_no': '2o76GcYaPSwMXFJd6wQsJX'}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-29 20:35:49,925] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 05:36:19,956] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 05:43:21,722] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 08:05:46,366] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 08:19:58,174] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 08:20:25,036] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 08:20:27,388] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 08:20:32,255] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 08:21:14,139] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 08:21:27,810] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 08:21:28,678] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 08:21:35,914] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 08:21:59,451] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 08:23:07,841] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 08:23:29,368] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 08:23:35,502] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 08:23:50,198] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 08:23:51,961] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 08:24:00,246] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 08:24:45,344] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 08:28:03,290] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 08:34:57,882] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 08:34:58,220] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 09:17:41,910] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 09:31:26,190] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 09:32:33,249] [INFO]: {'provider': 'username', 'Data': {'serial_no': 'bis1'}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 09:34:44,758] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 09:46:32,874] [INFO]: <Request 'http://3.215.183.155/api/services/v1/get_po_invoice' [POST]> [in /home/ubuntu/SIH-2020/app/routes.py:505]
[2020-07-30 09:46:32,874] [INFO]: reached po invoice 1 [in /home/ubuntu/SIH-2020/app/routes.py:511]
[2020-07-30 09:46:32,881] [INFO]: po_5f114408e257dd728e757d66.pdf [in /home/ubuntu/SIH-2020/app/routes.py:517]
[2020-07-30 09:46:32,972] [INFO]: http://3.215.183.155/static/po/po_5f114408e257dd728e757d66.pdf [in /home/ubuntu/SIH-2020/app/routes.py:523]
[2020-07-30 09:46:38,569] [INFO]: <Request 'http://3.215.183.155/api/services/v1/get_po_invoice' [POST]> [in /home/ubuntu/SIH-2020/app/routes.py:505]
[2020-07-30 09:46:38,569] [INFO]: reached po invoice 1 [in /home/ubuntu/SIH-2020/app/routes.py:511]
[2020-07-30 09:46:38,576] [INFO]: po_5f114408e257dd728e757d66.pdf [in /home/ubuntu/SIH-2020/app/routes.py:517]
[2020-07-30 09:46:38,649] [INFO]: http://3.215.183.155/static/po/po_5f114408e257dd728e757d66.pdf [in /home/ubuntu/SIH-2020/app/routes.py:523]
[2020-07-30 09:47:41,631] [INFO]: <Request 'http://3.215.183.155/api/services/v1/get_po_invoice' [POST]> [in /home/ubuntu/SIH-2020/app/routes.py:505]
[2020-07-30 09:47:41,631] [INFO]: reached po invoice 1 [in /home/ubuntu/SIH-2020/app/routes.py:511]
[2020-07-30 09:47:41,639] [INFO]: po_5f114408e257dd728e757d66.pdf [in /home/ubuntu/SIH-2020/app/routes.py:517]
[2020-07-30 09:47:41,713] [INFO]: http://3.215.183.155/static/po/po_5f114408e257dd728e757d66.pdf [in /home/ubuntu/SIH-2020/app/routes.py:523]
[2020-07-30 09:47:58,351] [INFO]: <Request 'http://3.215.183.155/api/services/v1/get_po_invoice' [POST]> [in /home/ubuntu/SIH-2020/app/routes.py:505]
[2020-07-30 09:47:58,352] [INFO]: reached po invoice 1 [in /home/ubuntu/SIH-2020/app/routes.py:511]
[2020-07-30 09:47:58,356] [ERROR]: Exception on /api/services/v1/get_po_invoice [POST] [in /usr/local/lib/python3.6/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ubuntu/SIH-2020/app/routes.py", line 514, in get_po_invoice
    content = db.po.find_one({'_id':ObjectId(data['Data']['po_id'])})
KeyError: 'po_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/SIH-2020/app/routes.py", line 528, in get_po_invoice
    logger.error(str(e) + "on line no: " + exc_tb.tb_lineno)
NameError: name 'logger' is not defined
[2020-07-30 09:52:25,386] [INFO]: <Request 'http://3.215.183.155/api/services/v1/get_so_invoice' [POST]> [in /home/ubuntu/SIH-2020/app/routes.py:540]
[2020-07-30 09:52:25,387] [INFO]: reached so invoice 1 [in /home/ubuntu/SIH-2020/app/routes.py:546]
[2020-07-30 09:52:25,395] [INFO]: so_5f1081f44cc54199378c7b2e.pdf [in /home/ubuntu/SIH-2020/app/routes.py:553]
[2020-07-30 09:52:25,464] [INFO]: http://3.215.183.155/static/so/so_5f1081f44cc54199378c7b2e.pdf [in /home/ubuntu/SIH-2020/app/routes.py:559]
[2020-07-30 09:52:33,077] [INFO]: <Request 'http://3.215.183.155/api/services/v1/get_so_invoice' [POST]> [in /home/ubuntu/SIH-2020/app/routes.py:540]
[2020-07-30 09:52:33,077] [INFO]: reached so invoice 1 [in /home/ubuntu/SIH-2020/app/routes.py:546]
[2020-07-30 09:52:33,089] [INFO]: so_5f113c6d09ca0c419118e66c.pdf [in /home/ubuntu/SIH-2020/app/routes.py:553]
[2020-07-30 09:52:33,163] [INFO]: http://3.215.183.155/static/so/so_5f113c6d09ca0c419118e66c.pdf [in /home/ubuntu/SIH-2020/app/routes.py:559]
[2020-07-30 09:52:41,649] [INFO]: <Request 'http://3.215.183.155/api/services/v1/get_so_invoice' [POST]> [in /home/ubuntu/SIH-2020/app/routes.py:540]
[2020-07-30 09:52:41,649] [INFO]: reached so invoice 1 [in /home/ubuntu/SIH-2020/app/routes.py:546]
[2020-07-30 09:52:41,658] [INFO]: so_5f157065719e10c7e20f4506.pdf [in /home/ubuntu/SIH-2020/app/routes.py:553]
[2020-07-30 09:52:41,731] [INFO]: http://3.215.183.155/static/so/so_5f157065719e10c7e20f4506.pdf [in /home/ubuntu/SIH-2020/app/routes.py:559]
