[2020-07-21 12:19:29,861] [INFO]: {'provider': 'username', 'Data': {'serial_no': '7zWdffH5DsiaUAbrPsKj2X'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 15:35:43,834] [INFO]: {'provider': 'username', 'Data': {'serial_no': 'cUQWnX8AKYHmSPRo8Vegdk'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 16:53:15,514] [INFO]: {'provider': 'username', 'Data': {'serial_no': '2o76GcYaPSwMXFJd6wQsJX'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 17:04:35,883] [INFO]: {'provider': 'username', 'Data': {'serial_no': 'FZJsBoW6KsUDkPnwZPU7jE'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 17:40:58,217] [INFO]: {'provider': 'username', 'Data': {'serial_no': None}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 17:56:26,531] [INFO]: {'provider': 'username', 'Data': {'serial_no': 'bis1'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 19:10:47,059] [INFO]: {'provider': 'username', 'Data': {'serial_no': 'PUCT8DkJNpU8vxgkALJGqd'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 19:12:43,405] [INFO]: {'provider': 'username', 'Data': {'serial_no': '2o76GcYaPSwMXFJd6wQsJX'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 19:13:09,063] [INFO]: {'provider': 'username', 'Data': {'serial_no': None}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 19:15:46,129] [INFO]: {'provider': 'username', 'Data': {'serial_no': None}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 19:16:04,499] [INFO]: {'provider': 'username', 'Data': {'serial_no': None}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 19:20:17,201] [INFO]: {'provider': 'username', 'Data': {'serial_no': 'P6ST4fyWsLTKikZ5532P2n'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 19:22:05,461] [INFO]: {'provider': 'username', 'Data': {'serial_no': None}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 19:22:26,125] [INFO]: {'provider': 'username', 'Data': {'serial_no': None}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 19:23:04,913] [INFO]: {'provider': 'username', 'Data': {'serial_no': None}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 19:25:38,464] [INFO]: {'provider': 'username', 'Data': {'serial_no': 'cUQWnX8AKYHmSPRo8Vegdk'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 19:33:33,964] [INFO]: {'provider': 'username', 'Data': {'serial_no': None}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 19:36:42,767] [INFO]: {'provider': 'username', 'Data': {'serial_no': '1'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 19:38:04,934] [INFO]: {'provider': 'username', 'Data': {'serial_no': '  '}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 19:38:36,314] [INFO]: {'provider': 'username', 'Data': {'serial_no': 'bis1'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 19:40:11,212] [INFO]: {'provider': 'username', 'Data': {'serial_no': '  '}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 19:43:08,077] [INFO]: {'provider': 'username', 'Data': {'serial_no': '  '}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 20:23:59,851] [ERROR]: Exception on /api/services/v1/order_finalize [POST] [in /home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ubuntu/SIH-2020/app/routes.py", line 508, in order_finalize
    assets = assets['assets']
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    the :attr:`before_first_request_funcs` and only exactly once per
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    @setupmethod
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    self.add_template_global(f, name=name)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    from io import StringIO
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    return f
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
  File "/home/ubuntu/SIH-2020/app/routes.py", line 534, in order_finalize
    logger.error(str(e) + "on line no: " + exc_tb.tb_lineno)
NameError: name 'logger' is not defined
[2020-07-23 20:24:06,735] [ERROR]: Exception on /api/services/v1/order_finalize [POST] [in /home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ubuntu/SIH-2020/app/routes.py", line 508, in order_finalize
    assets = assets['assets']
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    the :attr:`before_first_request_funcs` and only exactly once per
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    @setupmethod
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    self.add_template_global(f, name=name)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    from io import StringIO
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    return f
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
  File "/home/ubuntu/SIH-2020/app/routes.py", line 534, in order_finalize
    logger.error(str(e) + "on line no: " + exc_tb.tb_lineno)
NameError: name 'logger' is not defined
[2020-07-23 20:25:22,851] [ERROR]: Exception on /api/services/v1/order_finalize [POST] [in /home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ubuntu/SIH-2020/app/routes.py", line 508, in order_finalize
    assets = assets['assets']
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    the :attr:`before_first_request_funcs` and only exactly once per
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    @setupmethod
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    self.add_template_global(f, name=name)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    from io import StringIO
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    return f
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
  File "/home/ubuntu/SIH-2020/app/routes.py", line 534, in order_finalize
    logger.error(str(e) + "on line no: " + exc_tb.tb_lineno)
NameError: name 'logger' is not defined
[2020-07-23 20:26:19,533] [ERROR]: Exception on /api/services/v1/order_finalize [POST] [in /home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ubuntu/SIH-2020/app/routes.py", line 508, in order_finalize
    assets = assets['assets']
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    the :attr:`before_first_request_funcs` and only exactly once per
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    @setupmethod
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    self.add_template_global(f, name=name)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    from io import StringIO
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    return f
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
  File "/home/ubuntu/SIH-2020/app/routes.py", line 534, in order_finalize
    logger.error(str(e) + "on line no: " + exc_tb.tb_lineno)
NameError: name 'logger' is not defined
[2020-07-23 20:26:20,270] [ERROR]: Exception on /api/services/v1/order_finalize [POST] [in /home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ubuntu/SIH-2020/app/routes.py", line 508, in order_finalize
    assets = assets['assets']
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    the :attr:`before_first_request_funcs` and only exactly once per
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    @setupmethod
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    self.add_template_global(f, name=name)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    from io import StringIO
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    return f
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
  File "/home/ubuntu/SIH-2020/app/routes.py", line 534, in order_finalize
    logger.error(str(e) + "on line no: " + exc_tb.tb_lineno)
NameError: name 'logger' is not defined
