[2020-07-23 20:26:19,901] [ERROR]: Exception on /api/services/v1/order_finalize [POST] [in /home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ubuntu/SIH-2020/app/routes.py", line 508, in order_finalize
    assets = assets['assets']
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    the :attr:`before_first_request_funcs` and only exactly once per
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    @setupmethod
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    self.add_template_global(f, name=name)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    from io import StringIO
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    return f
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
  File "/home/ubuntu/SIH-2020/app/routes.py", line 534, in order_finalize
    logger.error(str(e) + "on line no: " + exc_tb.tb_lineno)
NameError: name 'logger' is not defined
[2020-07-23 20:26:20,357] [ERROR]: Exception on /api/services/v1/order_finalize [POST] [in /home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ubuntu/SIH-2020/app/routes.py", line 508, in order_finalize
    assets = assets['assets']
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    the :attr:`before_first_request_funcs` and only exactly once per
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    @setupmethod
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    self.add_template_global(f, name=name)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    from io import StringIO
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    return f
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
  File "/home/ubuntu/SIH-2020/app/routes.py", line 534, in order_finalize
    logger.error(str(e) + "on line no: " + exc_tb.tb_lineno)
NameError: name 'logger' is not defined
[2020-07-23 20:26:20,632] [ERROR]: Exception on /api/services/v1/order_finalize [POST] [in /home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ubuntu/SIH-2020/app/routes.py", line 508, in order_finalize
    assets = assets['assets']
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    the :attr:`before_first_request_funcs` and only exactly once per
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    @setupmethod
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    self.add_template_global(f, name=name)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    from io import StringIO
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    return f
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
  File "/home/ubuntu/SIH-2020/app/routes.py", line 534, in order_finalize
    logger.error(str(e) + "on line no: " + exc_tb.tb_lineno)
NameError: name 'logger' is not defined
[2020-07-23 20:26:20,787] [ERROR]: Exception on /api/services/v1/order_finalize [POST] [in /home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ubuntu/SIH-2020/app/routes.py", line 508, in order_finalize
    assets = assets['assets']
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    the :attr:`before_first_request_funcs` and only exactly once per
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    @setupmethod
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    self.add_template_global(f, name=name)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    from io import StringIO
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    return f
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
  File "/home/ubuntu/SIH-2020/app/routes.py", line 534, in order_finalize
    logger.error(str(e) + "on line no: " + exc_tb.tb_lineno)
NameError: name 'logger' is not defined
[2020-07-23 20:26:22,263] [ERROR]: Exception on /api/services/v1/order_finalize [POST] [in /home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ubuntu/SIH-2020/app/routes.py", line 508, in order_finalize
    assets = assets['assets']
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    the :attr:`before_first_request_funcs` and only exactly once per
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    @setupmethod
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    self.add_template_global(f, name=name)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    from io import StringIO
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    return f
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
  File "/home/ubuntu/SIH-2020/app/routes.py", line 534, in order_finalize
    logger.error(str(e) + "on line no: " + exc_tb.tb_lineno)
NameError: name 'logger' is not defined
[2020-07-23 20:39:25,543] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 20:47:32,771] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 20:49:29,401] [INFO]: {'provider': 'username', 'Data': {'serial_no': 'P6ST4fyWsLTKikZ5532P2n'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 20:50:05,673] [INFO]: {'provider': 'username', 'Data': {'serial_no': 'J9k7PV7m3uGocLPSbdJdYv'}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 20:50:15,263] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:906]
[2020-07-23 20:50:33,956] [ERROR]: Exception on /api/services/v1/order_finalize [POST] [in /home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ubuntu/SIH-2020/app/routes.py", line 508, in order_finalize
    assets = assets['assets']
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    the :attr:`before_first_request_funcs` and only exactly once per
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    @setupmethod
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    self.add_template_global(f, name=name)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    from io import StringIO
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    return f
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
  File "/home/ubuntu/SIH-2020/app/routes.py", line 534, in order_finalize
    logger.error(str(e) + "on line no: " + exc_tb.tb_lineno)
NameError: name 'logger' is not defined
