[2020-07-29 13:19:11,900] [INFO]: <Job 508a5b1c-31dd-4a73-a8d4-4349355ca583: app.tasks.transfer_n_assets('manav_broker', 'random', '8eM7PJv7xBTQSmG6rTwMx55EiomP76H96C9xQfCBwWTA', 1, ['cUQWnX8AKYHmSPRo8Vegdk'])> [in /home/ubuntu/SIH-2020/app/models.py:31]
[2020-07-29 13:19:12,622] [INFO]: Supply Chain Startup [in ./app/__init__.py:54]
[2020-07-29 13:19:31,569] [INFO]: <Request 'http://3.215.183.155/api/services/v1/get_so_invoice' [POST]> [in /home/ubuntu/SIH-2020/app/routes.py:540]
[2020-07-29 13:19:31,569] [INFO]: reached so invoice 1 [in /home/ubuntu/SIH-2020/app/routes.py:546]
[2020-07-29 13:19:31,577] [INFO]: so_5f21767c049dac9f7ccc8c2e.pdf [in /home/ubuntu/SIH-2020/app/routes.py:553]
[2020-07-29 13:19:31,664] [INFO]: http://3.215.183.155/static/so/so_5f21767c049dac9f7ccc8c2e.pdf [in /home/ubuntu/SIH-2020/app/routes.py:559]
[2020-07-29 14:29:39,598] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-29 14:29:39,737] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-29 15:20:26,163] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-29 15:20:26,283] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-29 17:44:19,944] [INFO]: {'provider': 'username', 'Data': {'serial_no': 'HzNuR53yopNwLzEvdAbC9e'}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-29 17:56:48,255] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-29 19:45:32,506] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-29 19:45:32,557] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-29 20:34:37,547] [INFO]: {'provider': 'username', 'Data': {'serial_no': '2o76GcYaPSwMXFJd6wQsJX'}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-29 20:37:08,182] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' bis1'}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 05:35:27,948] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 05:36:44,296] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 05:44:16,694] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 05:45:35,083] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 07:59:42,095] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 08:05:46,507] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 08:20:22,896] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 08:21:10,054] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 08:21:43,712] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 08:22:04,557] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 08:22:45,248] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 08:22:56,389] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 08:24:34,286] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 08:24:53,296] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 08:26:31,964] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 08:26:32,253] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 08:27:30,014] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 08:28:03,624] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 08:30:19,678] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 08:32:06,556] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 08:34:35,898] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 08:34:36,213] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 09:17:42,071] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 09:21:35,247] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 09:21:35,585] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 09:31:26,069] [INFO]: {'provider': 'username', 'Data': {'serial_no': ' '}} [in /home/ubuntu/SIH-2020/app/routes.py:995]
[2020-07-30 09:47:10,681] [INFO]: <Request 'http://3.215.183.155/api/services/v1/get_po_invoice' [POST]> [in /home/ubuntu/SIH-2020/app/routes.py:505]
[2020-07-30 09:47:10,681] [INFO]: reached po invoice 1 [in /home/ubuntu/SIH-2020/app/routes.py:511]
[2020-07-30 09:47:10,688] [INFO]: po_5f157208ea95723b48ff59f7.pdf [in /home/ubuntu/SIH-2020/app/routes.py:517]
[2020-07-30 09:47:10,760] [INFO]: http://3.215.183.155/static/po/po_5f157208ea95723b48ff59f7.pdf [in /home/ubuntu/SIH-2020/app/routes.py:523]
[2020-07-30 09:47:42,911] [INFO]: <Request 'http://3.215.183.155/api/services/v1/get_po_invoice' [POST]> [in /home/ubuntu/SIH-2020/app/routes.py:505]
[2020-07-30 09:47:42,912] [INFO]: reached po invoice 1 [in /home/ubuntu/SIH-2020/app/routes.py:511]
[2020-07-30 09:47:42,917] [ERROR]: Exception on /api/services/v1/get_po_invoice [POST] [in /usr/local/lib/python3.6/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ubuntu/SIH-2020/app/routes.py", line 514, in get_po_invoice
    content = db.po.find_one({'_id':ObjectId(data['Data']['po_id'])})
KeyError: 'po_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/SIH-2020/app/routes.py", line 528, in get_po_invoice
    logger.error(str(e) + "on line no: " + exc_tb.tb_lineno)
NameError: name 'logger' is not defined
[2020-07-30 09:47:57,455] [INFO]: <Request 'http://3.215.183.155/api/services/v1/get_po_invoice' [POST]> [in /home/ubuntu/SIH-2020/app/routes.py:505]
[2020-07-30 09:47:57,456] [INFO]: reached po invoice 1 [in /home/ubuntu/SIH-2020/app/routes.py:511]
[2020-07-30 09:47:57,463] [INFO]: po_5f114408e257dd728e757d66.pdf [in /home/ubuntu/SIH-2020/app/routes.py:517]
[2020-07-30 09:47:57,536] [INFO]: http://3.215.183.155/static/po/po_5f114408e257dd728e757d66.pdf [in /home/ubuntu/SIH-2020/app/routes.py:523]
[2020-07-30 09:51:59,462] [INFO]: <Request 'http://3.215.183.155/api/services/v1/get_so_invoice' [POST]> [in /home/ubuntu/SIH-2020/app/routes.py:540]
[2020-07-30 09:51:59,463] [INFO]: reached so invoice 1 [in /home/ubuntu/SIH-2020/app/routes.py:546]
[2020-07-30 09:51:59,471] [INFO]: so_5f1081f44cc54199378c7b2e.pdf [in /home/ubuntu/SIH-2020/app/routes.py:553]
[2020-07-30 09:51:59,540] [INFO]: http://3.215.183.155/static/so/so_5f1081f44cc54199378c7b2e.pdf [in /home/ubuntu/SIH-2020/app/routes.py:559]
[2020-07-30 09:52:34,585] [INFO]: <Request 'http://3.215.183.155/api/services/v1/get_so_invoice' [POST]> [in /home/ubuntu/SIH-2020/app/routes.py:540]
[2020-07-30 09:52:34,585] [INFO]: reached so invoice 1 [in /home/ubuntu/SIH-2020/app/routes.py:546]
